const oldProductList =  [
    {
      id: 1,
      name: "Cap",
      category: "Hats",
      price: 828,
      stock: 25,
    },
    {
      id: 2,
      name: "2 Color T-Shirt",
      category: "Hats",
      price: 144,
      stock: 43,
    },
    {
      id: 3,
      name: "Polo Tshirt",
      category: "Men's clothes",
      price: 28,
      stock: 123,
    },
    {
      id: 4,
      name: "Couple Set",
      category: "Men's clothes",
      price: 85,
      stock: 33,
    },
    {
      id: 5,
      name: "Collection",
      category: "Collection",
      price: 113,
      stock: 11,
    },
    {
      id: 6,
      name: "Balt Bag",
      category: "Collection",
      price: 28,
      stock: 123,
    },
    {
      id: 7,
      name: "Female Polo T-Shirt",
      category: "Women's clothes",
      price: 92,
      stock: 323,
    },
    {
      id: 8,
      name: "Half Pant",
      category: "Women's clothes",
      price: 35,
      stock: 52,
    },
    {
      id: 9,
      name: "Bag",
      category: "Accessories",
      price: 13,
      stock: 25,
    },

    {
      id: 10,
      name: "Glasses",
      category: "Glasses",
      price: 828,
      stock: 30,
    },
    {
      id: 11,
      name: "Nike Hat",
      category: "Hats",
      price: 144,
      stock: 20,
    },
    {
      id: 12,
      name: "Adidas Shoes",
      category: "Shoes",
      price: 28,
      stock: 19,
    },
    {
      id: 13,
      name: "Luis glasses",
      category: "Glasses",
      price: 85,
      stock: 30,
    },
    {
      id: 14,
      name: "kids T-Shirt",
      category: "T-Shirts",
      price: 113,
      stock: 75,
    },
    {
      id: 15,
      name: "Sandals",
      category: "Shoes",
      price: 28,
      stock: 12,
    },
    {
      id: 16,
      name: "Gucci Bag",
      category: "Accessories",
      price: 25,
      stock: 13,
    },
    {
      id: 17,
      name: "Sport Shoes",
      category: "Shoes",
      price: 92,
      stock: 18,
    },
    {
      id: 18,
      name: "Nasa T-Shirt",
      category: "T-Shirts",
      price: 35,
      stock: 27,
    },
    {
      id: 19,
      name: "American Pants",
      category: "Pants",
      price: 13,
      stock: 43,
    },
    {
      id: 20,
      name: "Female T-Shirt",
      category: "Women's clothes",
      price: 25,
      stock: 10,
    },
  ];

const productList = [
  {
    "id": 1,
    "product": "Syringe",
    "details": "Description of syringe, commonly used in medical settings.",
    "price": 62.11,
    "location_id": 9,
    "supplier_id": 5,
    "stock": 117,
    "reorder": 14,
    "exp_date": "2032-06-02"
  },
  {
      "id": 2,
      "product": "Bandage",
      "details": "Description of bandage, commonly used in medical settings.",
      "price": 120.54,
      "location_id": 5,
      "supplier_id": 5,
      "stock": 975,
      "reorder": 24,
      "exp_date": "2033-04-24"
  },
  {
      "id": 3,
      "product": "Thermometer",
      "details": "Description of thermometer, commonly used in medical settings.",
      "price": 391.15,
      "location_id": 3,
      "supplier_id": 1,
      "stock": 229,
      "reorder": 44,
      "exp_date": "2025-11-24"
  },
  {
      "id": 4,
      "product": "Stethoscope",
      "details": "Description of stethoscope, commonly used in medical settings.",
      "price": 139.87,
      "location_id": 1,
      "supplier_id": 8,
      "stock": 10,
      "reorder": 21,
      "exp_date": "2029-04-11"
  },
  {
      "id": 5,
      "product": "Surgical Mask",
      "details": "Description of surgical mask, commonly used in medical settings.",
      "price": 398.21,
      "location_id": 1,
      "supplier_id": 1,
      "stock": 984,
      "reorder": 39,
      "exp_date": "2027-01-11"
  },
  {
      "id": 6,
      "product": "Gloves",
      "details": "Description of gloves, commonly used in medical settings.",
      "price": 257.19,
      "location_id": 8,
      "supplier_id": 5,
      "stock": 660,
      "reorder": 33,
      "exp_date": "2030-12-12"
  },
  {
      "id": 7,
      "product": "IV Drip",
      "details": "Description of iv drip, commonly used in medical settings.",
      "price": 123.36,
      "location_id": 2,
      "supplier_id": 7,
      "stock": 207,
      "reorder": 31,
      "exp_date": "2027-05-09"
  },
  {
      "id": 8,
      "product": "Blood Pressure Monitor",
      "details": "Description of blood pressure monitor, commonly used in medical settings.",
      "price": 418.47,
      "location_id": 2,
      "supplier_id": 4,
      "stock": 20,
      "reorder": 24,
      "exp_date": "2033-12-31"
  },
  {
      "id": 9,
      "product": "Wheelchair",
      "details": "Description of wheelchair, commonly used in medical settings.",
      "price": 256.43,
      "location_id": 2,
      "supplier_id": 6,
      "stock": 69,
      "reorder": 22,
      "exp_date": "2031-10-27"
  },
  {
      "id": 10,
      "product": "Crutches",
      "details": "Description of crutches, commonly used in medical settings.",
      "price": 420.06,
      "location_id": 3,
      "supplier_id": 3,
      "stock": 134,
      "reorder": 40,
      "exp_date": "2030-09-08"
  },
  {
      "id": 11,
      "product": "Oximeter",
      "details": "Description of oximeter, commonly used in medical settings.",
      "price": 105.77,
      "location_id": 9,
      "supplier_id": 1,
      "stock": 133,
      "reorder": 36,
      "exp_date": "2028-06-02"
  },
  {
      "id": 12,
      "product": "Defibrillator",
      "details": "Description of defibrillator, commonly used in medical settings.",
      "price": 450.03,
      "location_id": 5,
      "supplier_id": 6,
      "stock": 160,
      "reorder": 13,
      "exp_date": "2025-02-18"
  },
  {
      "id": 13,
      "product": "Scalpel",
      "details": "Description of scalpel, commonly used in medical settings.",
      "price": 478.66,
      "location_id": 1,
      "supplier_id": 1,
      "stock": 727,
      "reorder": 43,
      "exp_date": "2029-06-29"
  },
  {
      "id": 14,
      "product": "Cotton Swabs",
      "details": "Description of cotton swabs, commonly used in medical settings.",
      "price": 492.93,
      "location_id": 9,
      "supplier_id": 6,
      "stock": 375,
      "reorder": 35,
      "exp_date": "2025-06-10"
  },
  {
      "id": 15,
      "product": "Antiseptic Solution",
      "details": "Description of antiseptic solution, commonly used in medical settings.",
      "price": 370.81,
      "location_id": 5,
      "supplier_id": 1,
      "stock": 816,
      "reorder": 44,
      "exp_date": "2026-05-01"
  },
  {
      "id": 16,
      "product": "Medical Gown",
      "details": "Description of medical gown, commonly used in medical settings.",
      "price": 470.47,
      "location_id": 2,
      "supplier_id": 3,
      "stock": 544,
      "reorder": 31,
      "exp_date": "2032-12-25"
  },
  {
      "id": 17,
      "product": "ECG Machine",
      "details": "Description of ecg machine, commonly used in medical settings.",
      "price": 42.75,
      "location_id": 9,
      "supplier_id": 3,
      "stock": 707,
      "reorder": 45,
      "exp_date": "2032-09-27"
  },
  {
      "id": 18,
      "product": "Surgical Table",
      "details": "Description of surgical table, commonly used in medical settings.",
      "price": 332.1,
      "location_id": 4,
      "supplier_id": 4,
      "stock": 636,
      "reorder": 38,
      "exp_date": "2025-06-28"
  },
  {
      "id": 19,
      "product": "Ultrasound Gel",
      "details": "Description of ultrasound gel, commonly used in medical settings.",
      "price": 289.21,
      "location_id": 8,
      "supplier_id": 5,
      "stock": 508,
      "reorder": 22,
      "exp_date": "2026-04-27"
  },
  {
      "id": 20,
      "product": "Hand Sanitizer",
      "details": "Description of hand sanitizer, commonly used in medical settings.",
      "price": 64.51,
      "location_id": 1,
      "supplier_id": 8,
      "stock": 284,
      "reorder": 21,
      "exp_date": "2030-09-13"
  }
];
export default productList;